# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
