# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
